---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates a cross account role for managing AWS accounts.
Outputs:
  RoleARN:
    Description: The ARN of the role that can be assumed by the other account.
    Value:
      Fn::GetAtt:
      - AWSAllAccountsRole
      - Arn
Parameters:
  ExternalID:
    Description: The External ID that will be required to assume the role.
    MinLength: '60'
    NoEcho: 'true'
    Type: String
    Default: u3xpnwsr6d5fwtno2ogok3gdo2w0y0ksqdekm41dme5maqcv5cmusrhjaqk6l5g4
  SharedServicesAccountNumber:
    AllowedPattern: "[0-9]+"
    Description: The 12 digit AWS account number to grant access to.
    MaxLength: '12'
    MinLength: '12'
    Type: String
    Default: '612698589016'
Resources:
  AWSAllAccountsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSAllAccountsRole
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId:
                Ref: ExternalID
          Effect: Allow
          Principal:
            AWS:
              !Sub "arn:aws:iam::${SharedServicesAccountNumber}:root"
          Sid: ''
        Version: '2012-10-17'
      Path: "/"
      Policies:
      - PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Resource:
                - !Sub "arn:aws:iam::*:role/OrganizationAccountAccessRole"
          Version: '2012-10-17'
        PolicyName: AWSAllAccountsPolicy